default: &default
  adapter: postgresql
  encoding: unicode
  username: cyrax
  password:

development:
  <<: *default
  database: chat_development

test:
  <<: *default
  database: chat_test

production:
  <<: *default
  database: chat_production
